FROM python:3.6.4
MAINTAINER Rajan Paneru <paneru.rajan@gmail.com>

# Install node
# Ref: https://deb.nodesource.com/setup_12.x
RUN \
  curl -sL https://deb.nodesource.com/setup_12.x | bash - && \
  apt-get install -yqq nodejs